import React from "react";
import Head from "next/head";

export const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ? title + " OSum" : "OSum"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <main>{children}</main>
      <footer></footer>
    </>
  );
};
