const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Service Shoes",
      slug: "service-shoe",
      category: "shoes",
      image: "/images/shoe1.jpg",
      price: 70,
      brand: "Bata",
      rating: 4,
      numReviews: 8,
      countInStock: 4,
      description: "its a great white shoe",
    },
    {
      name: "Service Don Carlos",
      slug: "don-carlos",
      category: "shoes",
      image: "/images/shoe2.jpg",
      price: 60,
      brand: "service",
      rating: 4.5,
      numReviews: 4,
      countInStock: 15,
      description: "good casual brown shoes",
    },
    {
      name: "Mili fashion shoes",
      slug: "mili-shoes",
      category: "shoe",
      image: "/images/shoe3.jpg",
      price: 90,
      brand: "Mili",
      rating: 4,
      numReviews: 7,
      countInStock: 10,
      description: "good durable fashion shoes from mili",
    },
    {
      name: "Nike sneekers",
      slug: "nike-sneekers",
      category: "shoe",
      image: "/images/shoe4.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.6,
      numReviews: 10,
      countInStock: 8,
      description: "good durable fashion sneakers from nike",
    },
    {
      name: "Nike white shoes",
      slug: "nike-white",
      category: "shoe",
      image: "/images/shoe5.jpg",
      price: 150,
      brand: "Nike",
      rating: 4.6,
      numReviews: 10,
      countInStock: 5,
      description: "good durable white shoe from nike",
    },
    {
      name: "Green hush pupies shoes",
      slug: "green-shoes",
      category: "shoe",
      image: "/images/shoe6.jpg",
      price: 150,
      brand: "Hush pupies",
      rating: 3.5,
      numReviews: 4,
      countInStock: 6,
      description: "good durable fashion shoes from hush pupies",
    },
  ],
};
export default data;
